### ISSUE TITLE
[Bug] Can't handle keypresses after clack session

### ISSUE THREAD

**Issue by Jwiggiff** [bombshell-dev/clack#134] opened 2023-08-04 16:13 UTC
**Environment**

- OS: `Windows 10`
- Node Version: `v18.16.1`
- Package: `@clack/prompts`
- Package Version: `^0.6.3`

**Describe the bug**
I am trying to use prompts to have kind a main menu for my program. After user selects an option, I am no longer using prompts. I have code to handle key presses using `readline.emitKeypressEvents(process.stdin);` which was working before I added in the prompts menu beforehand, but now it no longer works. I want to be able to use prompts and then end the session and have it behave as normal.

**To Reproduce**
https://stackblitz.com/edit/node-22pky6?file=index.js

- Use prompts to make a select menu
- Try to handle keypresses manually afterwards

**Expected behavior**
Manual key handling works after prompts is done

**Comment by cpreston321** [comment] 2023-08-10 18:56
@Jwiggiff this issue should be fixed in the latest release `0.70.0`.

If not please re-open this issue.

Thanks!

**Comment by Jwiggiff** [comment] 2023-08-10 19:22
@cpreston321 Thank you for looking into this. It still seems to be an issue with the new release.

https://stackblitz.com/edit/node-22pky6?file=index.js

**Comment by mikenikles** [comment] 2023-08-27 04:05
I'll add this as a comment, but please let me know if you think it's a separate issue.

I recently added a spinner to my CLI and ever since, `Ctrl + C` is ignored after the spinner finished. I have  reproduction at https://stackblitz.com/edit/clack-prompts-69ciwh?file=index.js.

**Comment by cpreston321** [comment] 2023-08-27 13:42
@mikenikles I think this is a separate issue! If you want to create a issue so we can track! 

CC// @Mist3rBru

**Comment by Mist3rBru** [comment] 2023-08-27 16:17
This is a separate issue, I can work on it later

**Comment by tigawanna** [comment] 2023-09-17 10:26
any updates on this? trying to stop a process using ctrl + c is not working on Windows

**Comment by Mist3rBru** [comment] 2023-09-17 13:32
@tigawanna If you are trying `ctrl + c` after an spinner, it has been tracked by #155 and will be solved on next release.

**Comment by tigawanna** [comment] 2023-09-17 13:33
🙏

**Comment by luisvinicius09** [comment] 2024-02-21 02:10
Any updates? Or workaround?

**Comment by luisvinicius09** [comment] 2024-02-21 14:58
I made it work by just adding ```process.stdin.resume();``` after emitting the keypress and setting raw mode. @Jwiggiff can you check if that's a solution, we can close this issue?

I think this is not a clack's bug, I've tried similar code with inquirer and got the same results. By resuming the stdin everything works as intended.

**Comment by Jwiggiff** [comment] 2024-02-28 01:35
Thank you @luisvinicius09 that worked for me!

**Comment by luisvinicius09** [comment] 2024-06-19 19:26
@cpreston321 I believe this one can be closed.

**Closed** 2024-06-19 19:32 UTC
Labels: bug
